### ISSUE TITLE
URLs with port specifier are invalid

### ISSUE THREAD

**Issue by riker09** [zeke/redact-url#1]
This package uses the dependency `is-url`. Unfortunately `is-url` does not correctly validate URLs with a port specifier.

The url `amqp://user:pass@domain.tld:1234` is validated as invalid, although it is a perfectly valid URL.

I know that this project hasn't been maintained since four years, but I wanted to save other people some trouble.

**Comment by zeke** [comment]
Thanks, @riker09. I would happily accept a pull request that swaps out the URL detection without breaking the existing use cases. Do you want to give that a shot?

**Comment by riker09** [comment]
PR is out. Take a look.

**Comment by pablote** [comment]
Just run into this issue. Looks like fix is not pulled :/

**Comment by zeke** [comment]
Hey there. Just landed this in #3. This is fixed in redact-url@0.4.0 

`npm i redact-url@latest` and you should be good to go!

**Comment by zeke** [comment]
PS thanks for the original PR @riker09 👍
